### ISSUE TITLE
Expose paging variables for GET /v2/account/activities endpoints

### ISSUE THREAD

**Issue by ajmwagar** [d-e-s-o/apca#5]
Hey d-e-s-o,

I've been attempting to pull trade execution info from the Alpaca API.

As you can see from [their documentation](https://alpaca.markets/docs/api-documentation/api-v2/account-activities/) you need to use the `page_token` and `page_size` Query params to get more than the last 100 trades. 

We can also specify `desc` or `asc` to set the direction.

Would it be possible to expose these query params?

I'd attempt to do it myself, but I'm not entirely sure how your `Endpoint!` macro works.

**Comment by d-e-s-o** [comment]
Yeah, it's something that is on my TODO list, because I need it too, although not urgently. I looked at it briefly a while back and something about their design put me off. Will take another look.

**Comment by ajmwagar** [comment]
From what I can tell you just past the ID of the oldest activity you have
into page_token.

I’m unable to track P/L historically without accessing all of my trades.

The default caps this at 100.

**Comment by d-e-s-o** [comment]
Yep, sucks that they don't expose that properly, but perhaps it's for the better. I am [importing](https://github.com/d-e-s-o/apcaledge) all transactions into ledger and then have a script that spits out profit/loss per transaction or per-day. It works flawlessly, I have to say (and I wouldn't want to do it on the fly). But as you said it requires me to import fairly regularly because of the 100 item limit (has never been an issue so far, though).

**Comment by d-e-s-o** [comment]
It won't work in that case. I am relying on any trades not present in the ledger to be within the last 100 ones for the account. I don't do excessive amounts of trading yet, so that's why it has worked out so far. But it's also why I want this hooked up, too, because it will be a limitation eventually. In any case, I am working on getting `page_size` and `page_token` hooked up right now.

**Comment by ajmwagar** [comment]
Awesome! I appreciate it.

It's annoying because partial_fill is kinda useless for the ledger P/L from what I can tell.

I'm probably just going to store the ledger as a hash map of order Id and orders. Then sort by the timestamp when it's time to calculate P/L.

**Comment by d-e-s-o** [comment]
Partial fills shouldn't matter at all for the ledger, should they? The knowledge of how much you ordered is not present there.

Here is what seems to be a working version: https://github.com/d-e-s-o/apca/tree/topic/paging

Feel free to give it a spin. Will hopefully polish and merge it by the weekend. Not sure if I'll cut a new release immediately, though.

**Comment by ajmwagar** [comment]
This looks great.

I need to clean up my branches and merge this into my fork. Then I can play it.

**Comment by ajmwagar** [comment]
Your branch works great!

**Comment by d-e-s-o** [comment]
Awesome. Thanks for trying it out.

**Comment by d-e-s-o** [comment]
Change got merged into `master` now.
